name: tik_tok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  animated_splash_screen: ^1.3.0
  lottie: ^2.3.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  firebase_core: ^2.11.0
  video_player: ^2.4.7
  video_compress: ^3.1.2 
  timeago: ^3.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

