name: tik_tok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  animated_splash_screen: ^1.3.0
  lottie: ^1.4.1
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  video_player: ^2.4.7
  video_compress: ^3.1.1
  timeago: ^3.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

