// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg05bXHh58zcDkj-f1vUp5kd6rhTcSoUc',
    appId: '1:659609185298:web:49ff39081d4396ceed7ccb',
    messagingSenderId: '659609185298',
    projectId: 'tiktok-2ddae',
    authDomain: 'tiktok-2ddae.firebaseapp.com',
    storageBucket: 'tiktok-2ddae.appspot.com',
    measurementId: 'G-5SG0JTW2FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGt_NW88q19yIJ9EvdM4ARiv31GHjsmY',
    appId: '1:659609185298:android:418b207980002dabed7ccb',
    messagingSenderId: '659609185298',
    projectId: 'tiktok-2ddae',
    storageBucket: 'tiktok-2ddae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxIeRVzTDxMZ2PSGwOrGOkrkZoOVK6CBU',
    appId: '1:659609185298:ios:e49ce319f680135fed7ccb',
    messagingSenderId: '659609185298',
    projectId: 'tiktok-2ddae',
    storageBucket: 'tiktok-2ddae.appspot.com',
    iosClientId: '659609185298-67p1mp8945pkdimjha9ofp8lncilk9lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikTok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxIeRVzTDxMZ2PSGwOrGOkrkZoOVK6CBU',
    appId: '1:659609185298:ios:e49ce319f680135fed7ccb',
    messagingSenderId: '659609185298',
    projectId: 'tiktok-2ddae',
    storageBucket: 'tiktok-2ddae.appspot.com',
    iosClientId: '659609185298-67p1mp8945pkdimjha9ofp8lncilk9lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikTok',
  );
}
